language: cpp

compiler:
  - clang
 
before_script:
  - sudo apt-get update -y
  - sudo apt-get install clang-3.4 -y
  - sudo apt-get install libedit2 libedit-dev libdbus-1-3 libdbus-1-dev -y
  - mkdir build
  - cd ./build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DUSE_DBUS=off
  - make clean && make

script:
  - make run_test

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
