os:
  - linux
  - osx

language: cpp

sudo: required
dist: trusty

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-3.4
      - gcc-4.8
      - g++-4.8
      - libxml2-dev
      - libdbus-1-3
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - expect

before_install:
  - ./setup.sh -DCMAKE_BUILD_TYPE=DEBUG

install:
 - cd build
 - make

script:
  - ctest --output-on-failure

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
