language: cpp

matrix:
  include:
    # gcc 4.8
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=gcc-4.8 CXX_BIN=g++-4.8

    # gcc 4.9
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=gcc-4.9 CXX_BIN=g++-4.9

    # gcc 5
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=gcc-5 CXX_BIN=g++-5

    # gcc 6
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=gcc-6 CXX_BIN=g++-6

    # clang 3.5
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.5
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=clang-3.5 CXX_BIN=clang++-3.5

    # clang 3.6
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=clang-3.6 CXX_BIN=clang++-3.6

    # clang 3.7
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=clang-3.7 CXX_BIN=clang++-3.7

    # clang 3.8
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=clang-3.8 CXX_BIN=clang++-3.8

    # clang 3.9
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=clang-3.9 CXX_BIN=clang++-3.9

    # clang 4.0
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
      env: CC_BIN=clang-4.0 CXX_BIN=clang++-4.0

script:
  - mkdir build && cd build 
  - cmake .. -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=DEBUG
  - make -j2
  - ctest --output-on-failure

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
