language: cpp

matrix:
  include:
    # gcc 4.8
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-4.8 CXX_BIN=g++-4.8

    # gcc 4.9
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-4.9 CXX_BIN=g++-4.9

    # gcc 5
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-5 CXX_BIN=g++-5

    # gcc 6
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-6 CXX_BIN=g++-6

    # gcc 7
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-7 CXX_BIN=g++-7

    # gcc 7 (Release build)
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-7 CXX_BIN=g++-7 DUMMY=release
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=Release
        - ninja
        - ctest --output-on-failure


    # clang 3.5
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.5
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-3.5 CXX_BIN=clang++-3.5

    # clang 3.6
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-3.6 CXX_BIN=clang++-3.6

    # clang 3.7
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-3.7 CXX_BIN=clang++-3.7

    # clang 3.8
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-3.8 CXX_BIN=clang++-3.8

    # clang 3.9
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-3.9 CXX_BIN=clang++-3.9

    # clang 4.0
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-4.0 CXX_BIN=clang++-4.0

    # clang 5.0
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-5.0 CXX_BIN=clang++-5.0

    # clang 5.0 (Release build)
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-5.0 CXX_BIN=clang++-5.0 DUMMY=release
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=Release
        - ninja
        - ctest --output-on-failure

    # clang 5.0 with address sanitizer
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-5.0 CXX_BIN=clang++-5.0 DUMMY=address-sanitizer
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=debug -DSANITIZER=address
        - ninja
        - ctest --output-on-failure

    # clang 5.0 with undefined behavior sanitizer
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-5.0 CXX_BIN=clang++-5.0 DUMMY=undefined-behavior-sanitizer
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=debug -DSANITIZER=undefined
        - ninja
        - ctest --output-on-failure

    # clang 5.0 with fuzzing
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-5.0 CXX_BIN=clang++-5.0 DUMMY=fuzzing
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DFUZZING_BUILD_MODE=on
        - ninja
        - ctest --output-on-failure

    # clang 5.0 with USE_DBUS=OFF
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=clang-5.0 CXX_BIN=clang++-5.0 DUMMY=use-dbus-off
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=debug -DUSE_DBUS=OFF
        - ninja
        - ctest --output-on-failure


    # gcc6 with coverage
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libxml2-dev
            - libdbus-1-3
            - libdbus-glib-1-dev
            - expect
            - ninja-build
      env: CC_BIN=gcc-6 CXX_BIN=g++-6 OPTION="-DCMAKE_BUILD_TYPE=coverage"
      before_script:
        - pip install --user cpp-coveralls
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN $OPTION
        - ninja
        - ctest --output-on-failure
      after_success:
        - coveralls --gcov gcov-6 --gcov-options '\-lp' --exclude test --exclude tools --exclude ext --exclude fuzzing --exclude-pattern re2c-.* --exclude src/nextToken.re2c.cpp --exclude nextToken.cpp

script:
  - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=DEBUG
  - ninja
  - ctest --output-on-failure

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
