language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - libxml2-dev
            - libdbus-1-3
            - libdbus-1-dev
            - libdbus-glib-1-dev
            - expect

    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.4
            - libxml2-dev
            - libdbus-1-3
            - libdbus-1-dev
            - libdbus-glib-1-dev
            - expect

script:
  - cmake -DCMAKE_BUILD_TYPE=DEBUG
  - make
  - ctest --output-on-failure

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
