language: cpp

sudo: false

compiler:
  - clang

addons:
  apt:
    packages:
      - cmake
      - clang-3.4
      - libedit2
      - libedit-dev
      - libxml2-dev
      - libdbus-1-3
      - libdbus-1-dev

before_install:
  - mkdir build
  - cd ./build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DUSE_DBUS=off -DUSE_LOGGING=on

install: 
 - make

script:
  - make run_test

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
