language: cpp

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-3.4
      - gcc-4.8
      - g++-4.8
      - libxml2-dev
      - libdbus-1-3
      - libdbus-1-dev
      - expect

before_install:
  - ./setup.sh -DCMAKE_BUILD_TYPE=DEBUG -DUSE_DBUS=off

install:
 - cd build
 - make

script:
  - make run_test

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
