language: cpp

os: linux
sudo: required
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    # gcc 4.8
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - expect
            - ninja-build
      env: CXX_BIN=g++-4.8 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # gcc 4.9
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - expect
            - ninja-build
      env: CXX_BIN=g++-4.9 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # gcc 5
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - expect
            - ninja-build
      env: CXX_BIN=g++-5 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # gcc 6
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - expect
            - ninja-build
      env: CXX_BIN=g++-6 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # gcc 7
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - expect
            - ninja-build
      env: CXX_BIN=g++-7 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # gcc 8
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - expect
            - ninja-build
      env: CXX_BIN=g++-8 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # gcc 8 (Release build)
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - expect
            - ninja-build
      env: CXX_BIN=g++-8 DUMMY=release
      script:
        - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=Release
        - ninja
        - ctest --output-on-failure

#    # gcc 8 with LTO
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#          - ubuntu-toolchain-r-test
#          packages:
#          - g++-8
#          - expect
#          - ninja-build
#      env: CXX_BIN=g++-8 DUMMY=release
#      script:
#      - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=Release -DUSE_LTO=ON
#      - ninja
#      - ctest --output-on-failure


    # clang 3.5
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.5
            - expect
            - ninja-build
      env: CXX_BIN=clang++-3.5 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 3.6
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - expect
            - ninja-build
      env: CXX_BIN=clang++-3.6 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 3.7
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - expect
            - ninja-build
      env: CXX_BIN=clang++-3.7 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 3.8
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - expect
            - ninja-build
      env: CXX_BIN=clang++-3.8 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 3.9
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - expect
            - ninja-build
      env: CXX_BIN=clang++-3.9 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 4.0
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - expect
            - ninja-build
      env: CXX_BIN=clang++-4.0 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 5.0
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - expect
            - ninja-build
      env: CXX_BIN=clang++-5.0 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 6.0
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - expect
            - ninja-build
      env: CXX_BIN=clang++-6.0 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

  # clang 7.0
    - addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
          - clang-7
          - expect
          - ninja-build
      env: CXX_BIN=clang++-7 BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG"

    # clang 7.0 (Release build)
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - expect
            - ninja-build
      env: CXX_BIN=clang++-7 DUMMY=release
      script:
        - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=Release
        - ninja
        - ctest --output-on-failure

#    # clang 6.0 with LTO
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#          - ubuntu-toolchain-r-test
#          - llvm-toolchain-trusty-6.0
#          packages:
#          - clang-6.0
#          - expect
#          - ninja-build
#      env: CXX_BIN=clang++-6.0 DUMMY=lto
#      script:
#      - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=Release -DUSE_LTO=ON
#      - ninja
#      - ctest --output-on-failure

    # clang 7.0 with address sanitizer
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - expect
            - ninja-build
      env: CXX_BIN=clang++-7 DUMMY=address-sanitizer
      script:
        - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=debug -DSANITIZER=address
        - ninja
        - ctest --output-on-failure

    # clang 7.0 with undefined behavior sanitizer
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - expect
            - ninja-build
      env: CXX_BIN=clang++-7 DUMMY=undefined-behavior-sanitizer
      script:
        - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DCMAKE_BUILD_TYPE=debug -DSANITIZER=undefined
        - ninja
        - ctest --output-on-failure

    # clang 7.0 with fuzzing
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - expect
            - ninja-build
      env: CXX_BIN=clang++-7 DUMMY=fuzzing
      script:
        - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN -DFUZZING_BUILD_MODE=on
        - ninja
        - ctest --output-on-failure

    # gcc6 with coverage
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - expect
            - ninja-build
      env: CC_BIN=gcc-6 CXX_BIN=g++-6 OPTION="-DCMAKE_BUILD_TYPE=coverage"
      before_script:
        - pip install --user cpp-coveralls
      script:
        - cmake . -G Ninja -DCMAKE_C_COMPILER=$CC_BIN -DCMAKE_CXX_COMPILER=$CXX_BIN $OPTION
        - ninja
        - ctest --output-on-failure
      after_success:
        - coveralls --gcov gcov-6 --gcov-options '\-lp' --exclude test --exclude tools --exclude ext --exclude fuzzing --exclude-pattern .*-source --exclude-pattern re2c-.* --exclude src/nextToken.re2c.cpp --exclude nextToken.cpp

script:
  - cmake . -G Ninja -DCMAKE_CXX_COMPILER=$CXX_BIN $BUILD_TYPE
  - ninja
  - ctest --output-on-failure

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
