language: cpp

sudo: false

compiler:
  - clang

addons:
  apt:
    packages:
      - cmake
      - clang-3.4
      - libxml2-dev
      - libdbus-1-3
      - libdbus-1-dev

before_install:
  - ./setup.sh -DCMAKE_BUILD_TYPE=DEBUG -DUSE_DBUS=off -DUSE_LOGGING=on -DUSE_SAFE_CAST=on

install:
 - cd build
 - make

script:
  - make run_test

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
