language: cpp

compiler:
  - clang
 
before_script:
  - sudo apt-get update -y
  - sudo apt-get install clang-3.4 -y
  - sudo apt-get install libedit2 libedit-dev -y
  - mkdir build
  - cd ./build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
  - make clean && make

script:
  - make run_test

notifications:
  emails:
    - s.nagisa.xyz@gmail.com
  on_success: change
  on_failure: always
